### ISSUE TITLE
RC5 Support

### ISSUE THREAD

**Issue by FabioAntunes** [AngularClass/angular2-hmr#20]
Does angular2-hmr supports RC5? If so does anyone has an example?

I tried doing this:
```javascript 
export function main(initialHmrState?: any): Promise<any> {
  return platformBrowserDynamic().bootstrapModule(AppModule).catch(err => console.error(err));
}


if (process.env.ENV !== 'build') {
  // activate hot module reload
  let ngHmr = require('angular2-hmr');
  ngHmr.hotModuleReplacement(main, module);
} else {
  // bootstrap when document is ready
  document.addEventListener('DOMContentLoaded', () => main());
}
```

But then I get this whenever I change one file:
`webpack-hmr.js:73 Uncaught TypeError: Cannot read property 'nativeElement' of undefined`

**Comment by gdi2290** [comment]
thanks, fixed. here's an example of the new api
https://github.com/AngularClass/angular2-seed/blob/e5c2c3c2b8d8a96420d59d21f8e040a8f9d634c1/src/main.browser.ts#L34...L51

**Comment by FabioAntunes** [comment]
@gdi2290 is the `@angularclass/hmr` the new namespace? Because npm can't find that

**Comment by gdi2290** [comment]
@FabioAntunes  ya sorry I published it and the default was private so it's public now

**Comment by banxia-zhaoyue** [comment]
@gdi2290  I use "npm install @angularclass/hmr" but the console still says '@angularclass/hmr is not in the npm resgistry'. Why?
