### ISSUE TITLE
What's best practice to tell from development and production

### ISSUE THREAD

**Issue by elaijuh** [AngularClass/angular2-hmr#22]
So definitely I don't want HMR in production running, do I need to manually check the environment and then decide if to use this module or not?

Should I do this ?

```
if (<any>module.hot) { 
  // go HMR way
} else {
  // go normal bootstrap way
}
```

**Comment by gdi2290** [comment]
don't include the loader in production and the only thing you need from this lib is `bootloader` but you can remove that and bootstrap the normal way after the dom is ready

```
       {
          test: /\.ts$/,
          loaders: [
            'awesome-typescript-loader',
          ].concat(prod ? [] : '@angularclass/hmr-loader')
        },
```

**Comment by elaijuh** [comment]
well in this way, i still have things like `hrmOnInit`, `hmrOnDestroy` in my source code.

**Comment by gdi2290** [comment]
I could update `@angularclass/hmr-loader` to strip out the methods in prod mode that way you need to include the loader in prod. The methods won't be called at all without the loader

**Comment by elaijuh** [comment]
ok i think just let the those code in my source code, thanks

**Comment by gdi2290** [comment]
I updated the loader to allow switching to prod mode
https://github.com/AngularClass/angular2-seed/blob/master/webpack.config.ts#L80
