### ISSUE TITLE
`hmrOnInit` is executed after component's `ngOnInit`

### ISSUE THREAD

**Issue by snolflake** [AngularClass/angular2-hmr#24]
As you can see in the screenshot below, when my components are initialized the state isn't restored yet. Is this the wanted behavior? Perhaps could I hold the application bootstrap somehow until the state is restored?!

PS: I'm already using your latest modifications made on hmr and in the starter pack
PS2: On the log messages: "APP INITIALIZED" is at app module constructor and "COMPONENT INITIALIZED" at component ngOnInit

![screenshot from 2016-09-09 21-13-48](https://cloud.githubusercontent.com/assets/1047033/18406499/f7bd18aa-76d3-11e6-972f-70edc488e00a.png)

**Comment by snolflake** [comment]
For now I am working around this by setting on localStorage a "wait" flag when `hmrOnDestroy` is fired and providing async getters for on my store service. 
Suggestions for better solutions are welcome... :pensive:

**Comment by gdi2290** [comment]
use the `constructor` and check for `module.hot.data`

**Comment by snolflake** [comment]
Thanks! Much better now...

But still no way to hold up the _full_ app initialization until the data is restored? If not, fell free to close this issue, thanks Patrick!

**Comment by gdi2290** [comment]
so are you're saying you want to have data before bootstrapping? like for creating certain providers or something?

**Comment by snolflake** [comment]
I might have a wrong idea of how the application lifecycle goes with HMR, but I tough that what I'm trying to achieve was already the default behavior. I believe that after the replacement occurs this should be the order:

1. All injectables are instantiated (so they can be provided in the module decorator)
2. App module is instantiated
3. App state is restored on store service (hmrOnInit)
4. Continue remaining bootstrapping process (root component initialization, etc)
5. Child component is initialized and already has it's cache restored (so it doesn't fire a http request to fetch data)

For me step 3 happens only after step 5, and that's my problem...

**Comment by Dragomir-Ivanov** [comment]
What is the resolution for this one? @cvsguimaraes I am seeing the same, how did you resolved this?

**Comment by gdi2290** [comment]
hmrOnInit is ran after ngOnInit by design but I can change it to happen before bootstrap and introduce hmrAfterBootstrap. If you need something to happen before bootstrap you can use the constructor as I mentioned

**Comment by Dragomir-Ivanov** [comment]
Thanks @gdi2290, which component lifecycle hook is called after `hmrOnInit` so we can be sure APP_STORE is already set?

**Comment by gdi2290** [comment]
hmrOnInit is called right after bootstrap is done

**Comment by Dragomir-Ivanov** [comment]
So `ngAfterContentInit()` will do. Thanks.

ngAfterContentInit() | Respond after Angular projects external content into the component's view.Called once after the first ngDoCheck().

**Comment by hghammoud** [comment]
Hello, I integrated the hmr with ngrx. In my app on certain views I call a load action to load data using ngrx effects. Since its in a ngOnInit, the store is populated -> triggers all the actions of load success before the hmrInit is injected.

Which is dumb considering the data is already in the store (not injected yet). Is there a way (example)  to inject the store before the onInit is called on components?

I tried in the constructor of the appmodule, but the module.hot.data is empty. I also tried ngAfterContentInit() its still being called before the hmrInit.

Tnx

**Comment by hghammoud** [comment]
Any response would be greatly appreciated.

**Comment by hghammoud** [comment]
this was my solution instead of hooked it after the bootstrap

`export class AppRootModule {
	constructor(
		public appRef: ApplicationRef,
		private _m: NgModuleRef<any>,
		private _store: Store<any>
	) {
		if (environment.hmr && module['hot']) {
			module['hot']['accept']();
			if (module['hot']) {
				if (module['hot']['data']) {
					this.hmrOnInit(module['hot']['data']);
				}
				module['hot']['dispose'](store => {
					this.hmrOnDestroy(store);
					_m.destroy();
					this.hmrAfterDestroy(store);
				});
			}
		}
	}
	hmrOnInit(store) {
		Log.info('------- HMR init');
		if (!store || !store.rootState) return;
		Log.info('HMR store', store.rootState);
		// restore state by dispatch a SET_ROOT_STATE action
		if (store.rootState) {
			this._store.dispatch({
				type: 'SET_ROOT_STATE',
				payload: store.rootState,
			});
		}
		if ('restoreInputValues' in store) {
			store.restoreInputValues();
		}
		// this.appRef.tick();
		Object.keys(store).forEach(prop => delete store[prop]);
	}

	hmrOnDestroy(store) {
		Log.info('------- HMR OnDestroy');
		this._store.take(1).subscribe(s => (store.rootState = { ...s, hmr: true }));
		const cmpLocation = this.appRef.components.map(
			cmp => cmp.location.nativeElement
		);
		store.disposeOldHosts = createNewHosts(cmpLocation);
		store.restoreInputValues = createInputTransfer();
		removeNgStyles();
	}
	hmrAfterDestroy(store) {
		Log.info('------- HMR AfterDestroy');
		store.disposeOldHosts();
		delete store.disposeOldHosts;
	}
}`
