### ISSUE TITLE
EPEERINVALID with Webpack 2 and NPM 2

### ISSUE THREAD

**Issue by bisubus** [AngularClass/angular2-hmr#26]
The package has problems with `webpack@*` constraint in peerDependencies. It causes EPEERINVALID error with Webpack 2 and NPM 2:

> npm ERR! node v6.2.2
> npm ERR! npm  v2.15.11
> npm ERR! code EPEERINVALID
> 
> npm ERR! peerinvalid The package webpack@2.1.0-beta.22 does not satisfy its siblings' peerDependencies requirements!
> 
> npm ERR! peerinvalid Peer @angularclass/hmr@1.2.1 wants webpack@*

The same thing applies to `@angularclass/hmr-loader`.

**Comment by lostdalek** [comment]
I have the same issue, when I try to shrinkwrap with npm 3x:

> npm ERR! argv "/Users/user/.nvm/versions/node/v6.3.1/bin/node" "/Users/user/.nvm/versions/node/v6.3.1/bin/npm" "shrinkwrap"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3

>npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! peer invalid: webpack@*, required by @angularclass/hmr@1.2.0

**Comment by glebmachine** [comment]
+1

**Comment by gdi2290** [comment]
thanks, the latest release removes the peer dep
