### ISSUE TITLE
TypeError: Cannot read property 'insertBefore' of null

### ISSUE THREAD

**Issue by jlabaj** [AngularClass/angular2-hmr#39]
function createNewHosts(cmps) {
    var components = cmps.map(function (componentNode) {
        var newNode = document.createElement(componentNode.tagName);
        // display none
        var currentDisplay = newNode.style.display;
        newNode.style.display = 'none';
        var parentNode = componentNode.parentNode;
        parentNode.insertBefore(newNode, componentNode);
...

newNode is null after [HMR] Checking for updates on the server...
Why could this be?

Thanks

**Comment by gdi2290** [comment]
what version of angular are you using?

**Comment by jlabaj** [comment]
Soory, nevermind, I called the bootstrap twice:
platformBrowserDynamic().bootstrapModule(AppModule);

export function main(): Promise<any> {
    return platformBrowserDynamic()
        .bootstrapModule(AppModule)
        .then(decorateModuleRef)
        .catch(err => console.error(err));
}

**Comment by gdi2290** [comment]
kool, I'll close this issue then. If you run into anymore issues feel free to open another one 👍
